tring to fail

diff --git a/.github/workflows/whatever.yml b/.github/workflows/whatever.yml
--- a/.github/workflows/whatever.yml
+++ b/.github/workflows/whatever.yml
@@ -18,6 +18,9 @@ jobs:
       - name: Lint 🧐
         run: npm run lint
 
+      - name: Simulate an error
+        run: echo "About to fail" ; exit 1
+
       - name: Build 🏗️
         run: npm run build
 
